//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoolmanagementn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolmanagementEntities : DbContext
    {
        public SchoolmanagementEntities()
            : base("name=SchoolmanagementEntities")
        {
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StaffInformation> StaffInformations { get; set; }
        public virtual DbSet<StudentInformation> StudentInformations { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
    }
}
