//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoolmanagementn.Models
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserRegistration
    {
        [DisplayName("UserId")]
        [Required(ErrorMessage = "UserId is required")]
        public string UserId { get; set; }
        public string FullName { get; set; }
        public string Role { get; set; }
        public string PhoneNumber { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is required")] 
        public string Password { get; set; }
        public string EmailId { get; set; }
    }
}
